import React, { useCallback, useEffect, useState } from 'react';
import {
  Alert, Box, Button, Card, CardContent, Chip, CircularProgress,
  Dialog, DialogActions, DialogContent, DialogTitle,
  IconButton, Skeleton, Table, TableBody, TableCell,
  TableContainer, TableHead, TableRow, TextField, Typography
} from '@mui/material';
import { Add, Close, Download, Payment, Refresh } from '@mui/icons-material';
import { apiRequest } from '../../utils/api';
import { getStoredUser } from '../../utils/authSession';

const fmt = (n) => Number(n || 0).toLocaleString();

const statusColor = (s) =>
  s === 'paid' ? 'success' : s === 'processed' ? 'warning' : 'default';

const downloadPayrollCSV = (payroll) => {
  const header = 'Employee,Position,Shifts,Pay Per Shift (FCFA),Total Amount (FCFA)';
  const rows = (payroll.employees || []).map(e =>
    `"${e.name || ''}","${e.position || ''}",${e.shifts || 0},${e.payPerShift || 0},${e.totalAmount || 0}`
  );
  const summary = `\n"TOTAL","","","",${payroll.totalAmount || 0}`;
  const csv = [header, ...rows, summary].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Payroll-${(payroll.period || 'report').replace(/\s+/g, '-')}.csv`;
  a.click();
  URL.revokeObjectURL(url);
};

const printPayrollReport = (payroll, company) => {
  const rows = (payroll.employees || []).map(e => `<tr>
    <td>${e.name || '—'}</td>
    <td>${e.position || '—'}</td>
    <td style="text-align:center">${e.shifts || 0}</td>
    <td style="text-align:right">${fmt(e.payPerShift)} FCFA</td>
    <td style="text-align:right;font-weight:700">${fmt(e.totalAmount)} FCFA</td>
  </tr>`).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Payroll Report – ${payroll.period}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:Arial,sans-serif;color:#1a1a2e;background:#f5f7fa;padding:30px 20px}
    .wrap{max-width:800px;margin:auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)}
    .header{background:linear-gradient(135deg,#1565c0,#1976d2);color:#fff;padding:26px 32px}
    .header h1{font-size:20px;font-weight:800}
    .header p{font-size:13px;opacity:.8;margin-top:4px}
    .meta{display:flex;gap:12px;margin-top:12px;flex-wrap:wrap}
    .meta span{background:rgba(255,255,255,.18);border-radius:20px;padding:3px 14px;font-size:12px;font-weight:600}
    .body{padding:26px 32px}
    table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px}
    th{background:#f0f6ff;color:#1565c0;font-weight:700;padding:10px 12px;text-align:left;border-bottom:2px solid #dde8fa}
    td{padding:9px 12px;border-bottom:1px solid #f0f3f8}
    tr:last-child td{border:none}
    .totals{background:#e8f5e9;margin-top:16px;border-radius:8px;padding:14px 18px;display:flex;justify-content:space-between;align-items:center}
    .totals .lbl{font-size:15px;font-weight:700;color:#2e7d32}
    .totals .amt{font-size:20px;font-weight:800;color:#1b5e20}
    .footer{text-align:center;padding:16px 32px;border-top:1px solid #e3eaf5;font-size:11px;color:#94a3b8}
    @media print{body{background:none;padding:0}.wrap{box-shadow:none;border-radius:0}}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="header">
      <h1>AutoPay – Payroll Report</h1>
      <p>${company || ''}</p>
      <div class="meta">
        <span>PERIOD: ${payroll.period}</span>
        <span>EMPLOYEES: ${payroll.totalEmployees || (payroll.employees || []).length}</span>
        <span>STATUS: ${(payroll.status || '').toUpperCase()}</span>
      </div>
    </div>
    <div class="body">
      <table>
        <thead><tr>
          <th>Employee</th><th>Position</th>
          <th style="text-align:center">Shifts</th>
          <th style="text-align:right">Pay/Shift</th>
          <th style="text-align:right">Total</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <div class="totals">
        <span class="lbl">Total Payroll</span>
        <span class="amt">${fmt(payroll.totalAmount)} FCFA</span>
      </div>
    </div>
    <div class="footer">Generated by AutoPay &nbsp;·&nbsp; ${new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  </div>
  <script>window.onload=()=>window.print();</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
};

const PayrollProcessing = () => {
  const user = getStoredUser() || {};
  const [payrolls, setPayrolls] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [snack, setSnack] = useState('');

  const [detailOpen, setDetailOpen] = useState(false);
  const [selected, setSelected] = useState(null);
  const [processing, setProcessing] = useState(false);

  const [genOpen, setGenOpen] = useState(false);
  const [genForm, setGenForm] = useState({ period: '', startDate: '', endDate: '' });
  const [generating, setGenerating] = useState(false);

  const load = useCallback(async () => {
    try {
      setLoading(true);
      setError('');
      const data = await apiRequest('/payrolls');
      if (data?.success) setPayrolls(data.data || []);
      else setError(data?.message || 'Failed to load payrolls.');
    } catch {
      setError('Network error while loading payrolls.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleReview = (p) => { setSelected(p); setDetailOpen(true); };
  const handleDetailClose = () => { setDetailOpen(false); setSelected(null); };

  const handleProcess = async () => {
    if (!selected) return;
    try {
      setProcessing(true);
      const data = await apiRequest(`/payrolls/${selected._id}/process`, { method: 'PUT' });
      if (data?.success) {
        setSnack('Payroll marked as processed.');
        handleDetailClose();
        load();
      } else {
        setSnack(data?.message || 'Failed to process payroll.');
      }
    } catch (e) {
      setSnack(e.message || 'Error processing payroll.');
    } finally {
      setProcessing(false);
    }
  };

  const handleGenerate = async () => {
    if (!genForm.period || !genForm.startDate || !genForm.endDate) {
      setSnack('Please fill in all fields.');
      return;
    }
    try {
      setGenerating(true);
      const data = await apiRequest('/payrolls', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(genForm)
      });
      if (data?.success) {
        setSnack('Payroll generated successfully.');
        setGenOpen(false);
        setGenForm({ period: '', startDate: '', endDate: '' });
        load();
      } else {
        setSnack(data?.message || 'Failed to generate payroll.');
      }
    } catch (e) {
      setSnack(e.message || 'Error generating payroll.');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Box sx={{ p: { xs: 2, sm: 3 } }}>
      {snack && (
        <Alert severity="info" onClose={() => setSnack('')} sx={{ mb: 2 }}>
          {snack}
        </Alert>
      )}

      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 3, flexWrap: 'wrap', gap: 1 }}>
        <Typography variant="h5" fontWeight={700}>Payroll Processing</Typography>
        <Box sx={{ display: 'flex', gap: 1 }}>
          <Button size="small" startIcon={<Refresh />} onClick={load} disabled={loading} variant="outlined">
            Refresh
          </Button>
          <Button variant="contained" startIcon={<Add />} onClick={() => setGenOpen(true)}>
            Generate Payroll
          </Button>
        </Box>
      </Box>

      {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}

      <Card>
        <CardContent>
          <Typography variant="subtitle1" fontWeight={700} sx={{ mb: 2 }}>Payroll Records</Typography>
          {loading ? (
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              {[1, 2, 3].map(i => <Skeleton key={i} height={52} sx={{ borderRadius: 1 }} />)}
            </Box>
          ) : payrolls.length === 0 ? (
            <Typography color="text.secondary" sx={{ py: 4, textAlign: 'center' }}>
              No payrolls yet. Use "Generate Payroll" to create one.
            </Typography>
          ) : (
            <TableContainer sx={{ overflowX: 'auto' }}>
              <Table sx={{ minWidth: 500 }}>
                <TableHead>
                  <TableRow>
                    <TableCell>Period</TableCell>
                    <TableCell align="center">Employees</TableCell>
                    <TableCell align="right">Total Amount</TableCell>
                    <TableCell align="center">Status</TableCell>
                    <TableCell align="center">Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {payrolls.map(p => (
                    <TableRow key={p._id} hover>
                      <TableCell sx={{ fontWeight: 600 }}>{p.period}</TableCell>
                      <TableCell align="center">{p.totalEmployees}</TableCell>
                      <TableCell align="right" sx={{ fontWeight: 600 }}>{fmt(p.totalAmount)} FCFA</TableCell>
                      <TableCell align="center">
                        <Chip label={p.status} color={statusColor(p.status)} size="small" sx={{ textTransform: 'capitalize' }} />
                      </TableCell>
                      <TableCell align="center">
                        <Box sx={{ display: 'flex', gap: 0.5, justifyContent: 'center', flexWrap: 'wrap' }}>
                          <Button size="small" onClick={() => handleReview(p)} sx={{ fontSize: 12 }}>
                            Review
                          </Button>
                          <Button size="small" startIcon={<Download sx={{ fontSize: 15 }} />} onClick={() => printPayrollReport(p, user.company)} sx={{ fontSize: 12 }}>
                            Print
                          </Button>
                          <Button size="small" startIcon={<Download sx={{ fontSize: 15 }} />} onClick={() => downloadPayrollCSV(p)} sx={{ fontSize: 12 }}>
                            CSV
                          </Button>
                        </Box>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </CardContent>
      </Card>

      {/* Detail / Approve Dialog */}
      <Dialog open={detailOpen} onClose={handleDetailClose} maxWidth="md" fullWidth>
        <DialogTitle sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            Payroll – {selected?.period}
            <Chip label={selected?.status} color={statusColor(selected?.status)} size="small" sx={{ textTransform: 'capitalize' }} />
          </Box>
          <IconButton size="small" onClick={handleDetailClose}><Close /></IconButton>
        </DialogTitle>
        <DialogContent>
          <TableContainer sx={{ overflowX: 'auto' }}>
            <Table sx={{ minWidth: 400 }}>
              <TableHead>
                <TableRow>
                  <TableCell>Employee</TableCell>
                  <TableCell>Position</TableCell>
                  <TableCell align="center">Shifts</TableCell>
                  <TableCell align="right">Pay/Shift</TableCell>
                  <TableCell align="right">Total</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {(selected?.employees || []).map((e, i) => (
                  <TableRow key={i} hover>
                    <TableCell sx={{ fontWeight: 600 }}>{e.name}</TableCell>
                    <TableCell>{e.position || '—'}</TableCell>
                    <TableCell align="center">{e.shifts}</TableCell>
                    <TableCell align="right">{fmt(e.payPerShift)} FCFA</TableCell>
                    <TableCell align="right" sx={{ fontWeight: 700 }}>{fmt(e.totalAmount)} FCFA</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
          <Box sx={{ mt: 2, p: 2, bgcolor: 'action.hover', borderRadius: 2, display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: 1 }}>
            <Typography><strong>Total Employees:</strong> {selected?.totalEmployees}</Typography>
            <Typography fontWeight={700}><strong>Total Amount:</strong> {fmt(selected?.totalAmount)} FCFA</Typography>
          </Box>
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 2, gap: 1 }}>
          <Button onClick={handleDetailClose} variant="outlined">Close</Button>
          <Button onClick={() => selected && printPayrollReport(selected, user.company)} startIcon={<Download />} variant="outlined">
            Print Report
          </Button>
          {selected?.status === 'draft' && (
            <Button
              onClick={handleProcess}
              variant="contained"
              startIcon={processing ? <CircularProgress size={16} color="inherit" /> : <Payment />}
              disabled={processing}
            >
              {processing ? 'Processing…' : 'Mark as Processed'}
            </Button>
          )}
        </DialogActions>
      </Dialog>

      {/* Generate Payroll Dialog */}
      <Dialog open={genOpen} onClose={() => setGenOpen(false)} maxWidth="sm" fullWidth>
        <DialogTitle>Generate New Payroll</DialogTitle>
        <DialogContent>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
            <TextField
              label="Period label (e.g. May 2025)"
              value={genForm.period}
              onChange={e => setGenForm(f => ({ ...f, period: e.target.value }))}
              fullWidth
            />
            <TextField
              label="Start Date"
              type="date"
              value={genForm.startDate}
              onChange={e => setGenForm(f => ({ ...f, startDate: e.target.value }))}
              InputLabelProps={{ shrink: true }}
              fullWidth
            />
            <TextField
              label="End Date"
              type="date"
              value={genForm.endDate}
              onChange={e => setGenForm(f => ({ ...f, endDate: e.target.value }))}
              InputLabelProps={{ shrink: true }}
              fullWidth
            />
          </Box>
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 2 }}>
          <Button onClick={() => setGenOpen(false)} variant="outlined">Cancel</Button>
          <Button
            onClick={handleGenerate}
            variant="contained"
            disabled={generating}
            startIcon={generating ? <CircularProgress size={16} color="inherit" /> : <Add />}
          >
            {generating ? 'Generating…' : 'Generate'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default PayrollProcessing;
