import React, { useEffect, useState } from 'react';
import {
  Alert, Box, Button, Card, CardContent, Chip,
  Skeleton, Table, TableBody,
  TableCell, TableContainer, TableHead, TableRow, Typography
} from '@mui/material';
import { Download } from '@mui/icons-material';
import { apiRequest } from '../../utils/api';
import { getStoredUser } from '../../utils/authSession';

const fmt = (n) => Number(n || 0).toLocaleString();

const statusColor = (s) =>
  s === 'paid' ? 'success' : s === 'processed' ? 'warning' : 'default';

const printPayslip = (payment, user) => {
  const paid = payment.paidAt
    ? new Date(payment.paidAt).toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })
    : payment.status === 'paid' ? 'Paid' : 'Pending';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Payslip – ${payment.period}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:Arial,sans-serif;color:#1a1a2e;background:#f5f7fa;display:flex;justify-content:center;padding:40px 16px}
    .slip{background:#fff;width:100%;max-width:640px;border-radius:12px;box-shadow:0 4px 24px rgba(0,0,0,.10);overflow:hidden}
    .header{background:linear-gradient(135deg,#1565c0,#1976d2);color:#fff;padding:28px 32px}
    .header h1{font-size:22px;font-weight:800;letter-spacing:.5px}
    .header p{font-size:13px;opacity:.82;margin-top:4px}
    .badge{display:inline-block;background:rgba(255,255,255,.18);border-radius:20px;padding:3px 14px;font-size:12px;margin-top:10px;font-weight:600;letter-spacing:.4px}
    .body{padding:28px 32px}
    section{margin-bottom:22px}
    section h2{font-size:13px;font-weight:700;color:#1565c0;text-transform:uppercase;letter-spacing:.8px;border-bottom:1px solid #e3eaf5;padding-bottom:7px;margin-bottom:12px}
    .row{display:flex;justify-content:space-between;padding:7px 0;font-size:14px;border-bottom:1px dashed #f0f3f8}
    .row:last-child{border:none}
    .label{color:#64748b}
    .value{font-weight:600;color:#1a1a2e}
    .net{background:#e8f5e9;border-radius:8px;padding:14px 18px;display:flex;justify-content:space-between;align-items:center;margin-top:10px}
    .net .label{font-size:15px;font-weight:700;color:#2e7d32}
    .net .amount{font-size:20px;font-weight:800;color:#1b5e20}
    .footer{text-align:center;padding:18px 32px;border-top:1px solid #e3eaf5;font-size:11px;color:#94a3b8}
    @media print{body{background:none;padding:0}.slip{box-shadow:none;border-radius:0}}
  </style>
</head>
<body>
  <div class="slip">
    <div class="header">
      <h1>AutoPay</h1>
      <p>Employee Pay Slip</p>
      <div class="badge">PERIOD: ${payment.period}</div>
    </div>
    <div class="body">
      <section>
        <h2>Employee Details</h2>
        <div class="row"><span class="label">Full Name</span><span class="value">${user.name || '—'}</span></div>
        <div class="row"><span class="label">Position</span><span class="value">${user.position || '—'}</span></div>
        <div class="row"><span class="label">Company</span><span class="value">${user.company || '—'}</span></div>
        <div class="row"><span class="label">Email</span><span class="value">${user.email || '—'}</span></div>
      </section>
      <section>
        <h2>Pay Period</h2>
        <div class="row"><span class="label">Start Date</span><span class="value">${payment.startDate ? new Date(payment.startDate).toLocaleDateString('en-GB') : '—'}</span></div>
        <div class="row"><span class="label">End Date</span><span class="value">${payment.endDate ? new Date(payment.endDate).toLocaleDateString('en-GB') : '—'}</span></div>
        <div class="row"><span class="label">Payment Date</span><span class="value">${paid}</span></div>
        <div class="row"><span class="label">Status</span><span class="value">${payment.status?.toUpperCase()}</span></div>
      </section>
      <section>
        <h2>Earnings</h2>
        <div class="row"><span class="label">Shifts Worked</span><span class="value">${payment.shifts}</span></div>
        <div class="net">
          <span class="label">Net Pay</span>
          <span class="amount">${fmt(payment.amount)} FCFA</span>
        </div>
      </section>
    </div>
    <div class="footer">
      Generated by AutoPay &nbsp;·&nbsp; ${new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}
      <br/>This is a computer-generated document and requires no signature.
    </div>
  </div>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
};

const Payments = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const user = getStoredUser() || {};

  useEffect(() => {
    apiRequest('/payrolls/my-history')
      .then(data => {
        if (data?.success) setHistory(data.data || []);
        else setError(data?.message || 'Failed to load payment history.');
      })
      .catch(() => setError('Network error while loading payments.'))
      .finally(() => setLoading(false));
  }, []);

  return (
    <Box sx={{ p: { xs: 2, sm: 3 }, maxWidth: 900, mx: 'auto' }}>
      <Typography variant="h5" fontWeight={700} gutterBottom>My Payments</Typography>

      {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}

      <Card>
        <CardContent>
          <Typography variant="subtitle1" fontWeight={700} sx={{ mb: 2 }}>Payment History</Typography>

          {loading ? (
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              {[1, 2, 3].map(i => <Skeleton key={i} height={52} sx={{ borderRadius: 1 }} />)}
            </Box>
          ) : history.length === 0 ? (
            <Typography color="text.secondary" sx={{ py: 4, textAlign: 'center' }}>
              No payment records found yet.
            </Typography>
          ) : (
            <TableContainer sx={{ overflowX: 'auto' }}>
              <Table sx={{ minWidth: 420 }}>
                <TableHead>
                  <TableRow>
                    <TableCell>Period</TableCell>
                    <TableCell>Shifts</TableCell>
                    <TableCell>Amount</TableCell>
                    <TableCell>Status</TableCell>
                    <TableCell>Paid On</TableCell>
                    <TableCell align="center">Payslip</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {history.map((p) => (
                    <TableRow key={p._id} hover>
                      <TableCell sx={{ fontWeight: 600 }}>{p.period}</TableCell>
                      <TableCell>{p.shifts ?? '—'}</TableCell>
                      <TableCell sx={{ fontWeight: 600 }}>{fmt(p.amount)} FCFA</TableCell>
                      <TableCell>
                        <Chip label={p.status} color={statusColor(p.status)} size="small" sx={{ textTransform: 'capitalize' }} />
                      </TableCell>
                      <TableCell>
                        {p.paidAt
                          ? new Date(p.paidAt).toLocaleDateString('en-GB')
                          : <Typography variant="caption" color="text.disabled">—</Typography>}
                      </TableCell>
                      <TableCell align="center">
                        <Button
                          size="small"
                          startIcon={<Download sx={{ fontSize: 16 }} />}
                          onClick={() => printPayslip(p, user)}
                          disabled={p.status === 'draft'}
                          sx={{ textTransform: 'none', fontSize: 12 }}
                        >
                          Download
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </CardContent>
      </Card>

      {!loading && history.length > 0 && (
        <Box sx={{ mt: 2, p: 2, borderRadius: 2, bgcolor: 'action.hover', display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: 1 }}>
          <Typography variant="body2" color="text.secondary">
            Total paid: {history.filter(p => p.status === 'paid').length} payroll(s)
          </Typography>
          <Typography variant="body2" fontWeight={700}>
            Lifetime earnings: {fmt(history.filter(p => p.status === 'paid').reduce((s, p) => s + (p.amount || 0), 0))} FCFA
          </Typography>
        </Box>
      )}
    </Box>
  );
};

export default Payments;
